- README.md
- truckersmp-cli
The script should work like before, hopefully.
Changes are:
- use `$XDG_CACHE_HOME/truckermp-cli` with `$HOME/.cache/truckersmp-cli` fallback
- use existing local `truckersmp` if available for fallback
- possible to specify the mod path with `-d <path>`
- show help with `-h`
- `GAMEDIR` is optional to only update and validate the mod files
- catch wrong given `GAMEDIR`
- reduce the output of `wget`
- place temporary files in `/tmp` for the filelist and the checksums
I'm not sure about the reduced output of `wget` because it sometimes hangs forever because of the two download locations I have no clue of.
> Enhance start script

- README.md
- truckersmp-cli
With Proton aka. Steam Play there's no need for a full wine installation with Steam inside. You don't have to start up Steam in wine and then have to start TruckersMP, this can now handled trough the native Steam client you've had probably already open.
So this script aims to have an easy solution to run TruckersMP with [Proton (Steam Play, Wine)](https://steamcommunity.com/games/221410/announcements/detail/1696055855739350561) with an update function for the needed windows data files through [steamcmd](https://developer.valvesoftware.com/wiki/SteamCMD).
This probably needs some testing and a better name.
What do you think?
> Add proton wrapper

- truckersmp-cli
MOD downloading stopped working because the structure of "files.json" has been slightly changed.
This commit fixes it.
> Update JSON parsing (fix MOD downloading)

- truckersmp-cli
When `default` is the first item in `proton.json`, Proton AppId list will be empty.
This commit fixes the issue.
> create_arg_parser(): Fix potential empty Proton AppId list

- .github/workflows/build_and_upload_inject_program.yaml
- .github/workflows/check_main_script.yaml
- .github/workflows/check_proton_json.yaml
This PR adds GitHub Actions workflow file. *This doesn't change programs* but is useful for improving productivity.
This allows us to do some checks automatically when:
* new commits are pushed to `master` branch
* someone created a new PR against `master` branch
Currently it checks:
* `proton.json`
* Job name: `proton_json`
* Generate Proton AppId list from `proton.json`
* Check whether `proton.json` is valid
* `truckersmp-cli`
* Job name: `download_files`
* Check whether `download_files()` function works properly
* HTTP redirection handling is also tested
* Job name: `flake8`
* Check main script by flake8 with flake8-docstrings and flake8-import-order
* `truckersmp-cli.c`
* Job name: `build`
* Compile C source by mingw-w64
* Create binary .tar.xz files (GitHub Actions "Artifact" file) …
> Add GitHub Actions workflow files

- truckersmp-cli
As mentioned in #58 this is probably the easiest way to get the currently supported game versions.
It [queries the API](https://api.truckersmp.com/v2/version) and filters for relevant information.
Returns a dict of game-version pairs:
~~~
{
"truckersmp": "0.2.2.6.6",
"ets2": "1.36.2.55",
"ats": "1.36.1.40"
}
~~~
> Add function to retrieve current supported versions

- README.md
- truckersmp-cli
Closes #60 and #36.
* Check x86_64 version of libSDL2 on Linux
* README.md: Add "x86_64 version of SDL2" to "Dependencies > Required"
> SDL2 run-time checking and README update

- truckersmp-cli
This will automatically detect the branch which is needed to get the correct ETS2 or ATS version for being able to run TruckersMP. The branch can still be overwritten by `--branch`.
* `https://stats.truckersmp.com` will be parsed for the downgrade link `https://truckersmp.com/kb/26` and the message scanned for ETS2 and ATS. We may have to revisit this in case they adjust the message.
If there's a better way to get the version we will have _after_ an update or if an downgrade is needed we should also revisit this part.
This is largely based on your [comment](https://github.com/lhark/truckersmp-cli/issues/58#issuecomment-622728329).
* If a downgrade would be needed the currently supported version by TruckersMP will be fetched and guessed into SCS beta branch naming scheme. `temporary_1_36`
> Automatic branch detection

- truckersmp-cli
I'm sorry, it was being used only in `activate_native_d3dcompiler_47()`...
This PR fixes the issue.
> start_with_wine(): Use environment variable "WINE" if defined when starting game

- README.md
- truckersmp-cli
This will auto-detect the most recent steam account with saved credentials.
It's still possible to override the account name and the override is required if we're unable to get the account name automatically.
> Auto detect steam account

- Makefile
- README.md
This will run [genzshcomp](https://github.com/hhatto/genzshcomp) when found in `$PATH` when running `make`.
It will allow tab completions when we're storing the file `_truckersmp-cli` somewhere in the `$fpath`, probably `$PREFIX/share/zsh/site-functions/_truckersmp-cli`, later through `setup.py`.
I haven't found something similar for bash.
> Generate bash/zsh completions

- .gitignore
- MANIFEST.in
- setup.cfg
- setup.py
They allow us to provide our PyPI package.
This won't work until the file `RELEASE` is added to this repository, but I tested.
Project page on PyPI: https://pypi.org/project/truckersmp-cli/
> Provide setuptools files

- truckersmp_cli/__init__.py
Self update for release asset users and git repository users.
This implementation is simple and partially not based on my past idea.
* Don't put files into `$XDG_DATA_HOME/truckersmp-cli/`
* Unpack the archive file first, to make sure there is enough free disk space
Regarding `README.md`, it's better to add its description in #80.
> Implement "--self-update" option

- .github/workflows/auto_release.yaml
The automatic uploading requires a "secret" for the PyPI token,
which can be added only by repository owner (@lhark).
I can add the "secret" only to my forked repository
(kakurasan/truckersmp-cli) and tentatively I'll use
my forked repository for uploading our PyPI package.
Note: I need to keep master branch in sync with upstream.
Screenshot:
The secret `PYPI_TOKEN` is ready:
> GitHub Actions: Automatic uploading to PyPI

- README.md
- truckersmp_cli/__init__.py
This allows users not to press Enter key when Steam is ready.
Based on https://github.com/lhark/truckersmp-cli/pull/63#discussion_r423073700
Closes #58
> start_with_wine(): Wait for Steam to be running

- truckersmp_cli/__init__.py
When the default prefix is used with Wine, we append "pfx" to the prefix
to make sure Proton and Wine are using the same default.
But the "default Steam directory for Wine" uses the default path
without the "pfx".
This commit fixes this (an issue in #83).
> Fix default Steam directory for Wine when default prefix is used

- truckersmp_cli/__init__.py
This fixes invisible area in Steam client.
Steam client needs D3D11 and it should not be disabled
even if using OpenGL in games.
> wait_for_steam(): Add "-no-cef-sandbox" option to steam.exe

- .github/workflows/auto_release.yaml
The title of each release page is "*Release Release* [version]".
This changes it to "Release Version [version]".
> GitHub Actions: Change release name to "Version"

- README.md
- truckersmp_cli/__init__.py
This allows users to update games via Windows version of SteamCMD.
This is useful for non-Linux users.
~~Known issue: Password required both when executing SteamCMD ("FAILED login with invalid cached credentials") and starting Steam client~~
Note: Password required only for the first time.
> update_game(): Support Windows version of SteamCMD for Wine

- truckersmp_cli/__init__.py
If `WINEDLLOVERRIDES` is already defined when starting game with Wine, it's *replaced* with `d3d11=;dxgi=` or empty.
This fixes the issue.
> start_with_wine(): Append WINEDLLOVERRIDES value when disabling D3D11

- .github/workflows/check_main_script.yaml
- truckersmp-cli
This adds the GitHub Actions job for pylint checking.
* pylint can be installed via `pip`
* `-j2` option (use 2 processes) makes the job faster
* `-j0` (auto-detect the number of processors available to use) is also ok
* pylint doesn't like the name of main script `truckersmp-cli`
> GitHub Actions: Add pylint checking

- truckersmp_cli/truckersmp.py
* Rewrite part of docstring
* Check whether the returned JSON data has both `supported_game_version` and `supported_ats_game_version` before creating a dict object (Background: `KeyError` would be unhandled since 90bcb47 because of my mistake in #98)
* Output warning messages if something goes wrong
> Small improvements in get_supported_game_versions()

- README.md
- truckersmp_cli/args.py
- truckersmp_cli/main.py
- truckersmp_cli/utils.py
Note that mouse clicking won't work in other GUI apps while game is running.
SIZE must be 'WIDTHxHEIGHT' format (e.g. `1920x1080`).
See also https://github.com/lhark/truckersmp-cli/issues/90#issuecomment-680889525
> Add "--wine-desktop" option for DXVK tabbed-out rendering issue

- README.md
`pip` command is used to install packages for Python 2 (not 3) on some systems.
> README.md: Replace "pip" command with "python3 -m pip"

- .github/workflows/auto_release.yaml
Not sure whether this fixes autorelease tags issue, but we need to change this because the document was [updated](https://github.com/actions/checkout#Fetch-all-history-for-all-tags-and-branches).
> GitHub Actions: Checkout with "fetch-depth: 0" instead of "git fetch --prune --unshallow"

- truckersmp_cli/utils.py
See https://github.com/lhark/truckersmp-cli/issues/117#issuecomment-712903652 and https://github.com/lhark/truckersmp-cli/issues/117#issuecomment-713561126
Fixes #117
> check_steam_process(): Make sure that the prefix directory exists before running winedbg

- README.md
- truckersmp_cli/args.py
- truckersmp_cli/steamcmd.py
When using Proton we should avoid using the system wine as the versions probably differs.
Calling wine with a different version than the prefix results in the whole prefix being up- or downgraded by copying all necessary files to adjust to the calling wine version. With a working proton prefix this results in a prefix upgrade on updating the game files and a downgrade afterwards when starting the game.
Let's avoid this unnecessary waiting time and hard drive stress either by using protons wine version or by reconsidering the wine call.
https://github.com/lhark/truckersmp-cli/blob/master/truckersmp_cli/steamcmd.py#L123
> Avoid switching wine versions

- truckersmp-cli
- truckersmp_cli/main.py
`locale.setlocale()` should not be called in Python modules.
I should have fixed this in PR 73.
> main.py, truckersmp-cli: Move locale.setlocale() calls to truckersmp-cli

- truckersmp_cli/main.py
…so it's still possible to access the help text and version without having the executable present.
This avoids a race condition in our makefile.
https://github.com/lhark/truckersmp-cli/pull/141#issuecomment-754007312
> Move executable check behind argparser

- README.md
- truckersmp_cli/args.py
- truckersmp_cli/main.py
- truckersmp_cli/steamcmd.py
When both `--update` and `--proton` are specified, `update_game()` tries to update Proton every time.
This is not necessary when:
* User already installed Proton via Steam client (to play other Windows games) and `--protondir` is used when updating/playing
* In this case Proton is updated via Steam client
* User knows that Proton is up-to-date
* When user first updates ETS2 and next ATS (`truckersmp-cli --ets2 --proton --update` -> `truckersmp-cli --ats --proton --update`), the 2nd updating (for updating ATS) is redundant.
This PR adds `--skip-update-proton` option: If this option is specified and Proton is already installed, Proton is not updated.
Example: `truckersmp-cli --ets2 --proton --update && truckersmp-cli --ats --proton --update --skip-update-proton`
> update_game(): Allow to skip updating Proton if Proton is already installed

- truckersmp_cli/main.py
> main(): Use os.access() instead of open() to check executable

- truckersmp_cli/main.py
- truckersmp_cli/truckersmp.py
I think the branches are not very meaningful because they're used only for printing "Creating directory /path/to/dir" debug messages.
If the directory exists, `os.makedirs("/path/to/dir", exist_ok=True)` does nothing successfully. So we don't need to use `if` to "create a directory only when it doesn't exist".
> main.py, truckersmp.py: Remove branches that are used only for debug messages

- truckersmp_cli/main.py
`os.path.isdir()` returns `True` even if user is not allowed to access the directory.
It's better to also check whether user has permission to read/write/execute it.
> main(): Check whether user has permission to access fallback directory

- .github/workflows/auto_release.yaml
I have added PyPI token for uploading (`secrets.PYPI_TOKEN`) and it should work.
Note: I am still the "sole owner" of truckersmp-cli *on PyPI* and I would like to invite @lhark and @Lucki, but your PyPI usernames are required.
> GitHub Actions: Upload to PyPI when repo is "truckersmp-cli/truckersmp-cli"

- README.md
- truckersmp_cli/args.py
- truckersmp_cli/truckersmp.py
- truckersmp_cli/variables.py
This allows users to automatically determine branch name for downgraded version when updating with `--downgrade` option.
Instead, this PR removes automatic branch detection because it has stopped working.
Closes #162.
> Determine branch name for downgraded version when updating with "--downgrade" option

- README.md
- truckersmp_cli/args.py
This might be needed as a preparation for #167.
Depends on #165 because of `--downgrade` option.
```
$ truckersmp-cli (options...) [action] [game]
```
Name|Description
---|---
`start`|Start game
`update`|Update/install latest game
`downgrade`|Downgrade game (install game from `temporary_X_Y` branch)
`updateandstart`(or `ustart`)|`update` + `start`
`downgradeandstart`(or `dstart`)|`downgrade` + `start`
Name|Game
---|---
`ets2mp`|ETS2 multiplayer
`ets2`|ETS2 singleplayer
`atsmp`|ATS multiplayer
`ats`|ATS singleplayer
Name|Replacement
---|---
`--update`|Action (`update`, `ustart`)
`--downgrade`|Action (`downgrade`, `dstart`)
`--start`|Action (`start`, `ustart`, `dstart`)
`--singleplayer`|Game names (`ets2`, `ats`)
`--ets2`|Game names (`ets2mp`, `ets2`)
`--ats`|Game names (`atsmp`, `ats`)
> Support new syntax

- truckersmp_cli/main.py
- truckersmp_cli/utils.py
This PR splits `start_wine_discord_ipc_bridge()` into 2 parts:
* Checking and downloading Discord bridge: No changes
* Starting wine-discord-ipc-bridge: Create `subprocess.Popen` object in `start_with_proton()` (Note: This will be moved to Steam Runtime helper script in #159) / `start_with_wine()`
This PR also changes:
* The name of the function: `setup_wine_discord_ipc_bridge()`
* Return value: The path to `winediscordipcbridge.exe`
* This value is used when creating `subprocess.Popen` object
See https://github.com/truckersmp-cli/truckersmp-cli/pull/159#issuecomment-824843411
> start_wine_discord_ipc_bridge(): Don't start executable in this function

- truckersmp_cli/main.py
`R1732: Consider using 'with' for resource-allocating operations (consider-using-with)`
It seems the messages came from recent pylint change.
We need to suppress the messages because we don't always start wine-discord-ipc-bridge and *cannot use* `with` for `ipcbr_proc`.
> main.py: Suppress R1732

- .github/workflows/check_gen_completions.yaml
- Makefile
- README.md
- gen_completions
- truckersmp_cli/args.py
- truckersmp_cli/main.py
This PR adds `gen_completions` program that automatically generates bash/zsh completion files.
The generated files support our new syntax which was introduced by #170.
```
(bash)
$ ./gen_completions --bash-completion /path/to/bash_completion_file
(zsh)
$ ./gen_completions --zsh-completion /path/to/zsh_completion_file
(both)
$ ./gen_completions --bash-completion /path/to/bash_completion_file --zsh-completion /path/to/zsh_completion_file
```
* Generated completion files don't support deprecated options
* Users who use the completion files would migrate to new syntax
* `genzshcomp` is not needed anymore
> Autogenerate bash/zsh completion files

- .github/workflows/build_and_upload_inject_program.yaml
- README.md
- truckersmp-cli.c
- truckersmp_cli/args.py
- truckersmp_cli/main.py
This PR adds `--game-options=` option. The specified game options are passed to ATS/ETS2.
Closes #163.
Example: `--game-options="-nointro -64bit -sysmouse"`
@Lucki Don't forget to compile `truckersmp-cli.c` and replace original `truckersmp-cli.exe` with compiled executable before testing this.
> Allow to specify custom ATS/ETS2 launch options

- truckersmp_cli/utils.py
Used by default when available: https://github.com/ValveSoftware/Proton#runtime-config-options
Note: Currently Proton users are able to use fsync by default because we start games using `proton` command.
> utils.py: Respect "PROTON_NO_FSYNC"

- .pylintrc
- truckersmp_cli/main.py
- truckersmp_cli/steamruntime_helper.py
- truckersmp_cli/utils.py
* Read output line by line
* `print()` with `flush=True`
* Add exception handling for `UnicodeDecodeError`
> Improve printing child process output

- truckersmp_cli/main.py
Fixes #197
The new behavior: When `truckersmp-cli` is installed in `/usr`, it creates a temporary directory (`truckersmp-cli-steamruntime-sharing-workaround-*`), copies `steamruntime_helper.py` and `truckersmp-cli.exe` to the directory, and use them instead of installed files. The temporary directory is removed automatically when `truckersmp-cli` exits (including `sys.exit()`).
> Add /usr sharing workaround for system-wide installation

- .github/workflows/build_and_upload_inject_program.yaml
* `make clean` is now unnecessary because we removed `truckersmp-cli.exe` in #78 (Release 0.1.0)
* No need to generate completion files in the job
Partially written by @Lucki (https://github.com/truckersmp-cli/truckersmp-cli/pull/179#issuecomment-833514751).
> GitHub Actions: Get rid of unnecessary actions in "Build truckersmp-cli.exe"

- truckersmp_cli/utils.py
- truckersmp_cli/variables.py
`/path/to/prefix/dosdevices/[drive letter]:` path is actually used by Wine/Proton. `drive_c` is just the default directory name for the automatically created OS drive.
> activate_native_d3dcompiler_47(): Use "dosdevices/c:" instead of "drive_c"

- truckersmp_cli/steamcmd.py
Proton and Steam Linux Runtime can be installed without a Steam account.
> Use anonymous login for Proton and Steam Linux Runtime

- truckersmp_cli/main.py
- truckersmp_cli/utils.py
- truckersmp_cli/variables.py
I sent a Wine bug report "[TruckersMP: Multiplayer overlay is invisible when builtin d3dcompiler_47.dll is used](https://bugs.winehq.org/show_bug.cgi?id=50777)" in March 2021 but nothing changed as of June 2021.
I guess that it's quite difficult to fix that (= to implement something missing in Wine's builtin DLL?).
So I think that we should use the native version of `d3dcompiler_47.dll` by default.
This PR allows D3D11 users to omit `--activate-native-d3dcompiler-47` by checking whether `truckersmp-cli` needs to call `activate_native_d3dcompiler_47()`.
* If `--activate-native-d3dcompiler-47` is given, `activate_native_d3dcompiler_47()` is always called (multiplayer and singleplayer)
* If `--activate-native-d3dcompiler-47` is not given, `activate_native_d3dcompiler_47()` is called only …
> Use native d3dcompiler_47.dll by default when using D3D11

- truckersmp_cli/main.py
- truckersmp_cli/utils.py
This also reduces the number of local variables in `start_with_{proton,wine}()`.
> main.py, utils.py: Use an external function for printing environment variables and command line

- truckersmp_cli/args.py
- truckersmp_cli/configfile.py
- truckersmp_cli/main.py
- truckersmp_cli/steamruntime_helper.py
- truckersmp_cli/utils.py
- truckersmp_cli/variables.py
For part of #103.
This PR allows users to start *already installed* TrucksBook Client (`TB Client.exe`) and other third-party programs.
* *No automated setup for TrucksBook in this PR*
* ~~If `C:\Program Files (x86)\TrucksBook Client\TB Client.exe` is present and readable, `truckersmp-cli` automatically start it before the game~~
* ~~If `--without-trucksbook` is given, `truckersmp-cli` doesn't start it~~
* ~~According to https://github.com/truckersmp-cli/truckersmp-cli/pull/159#issuecomment-841293257, TrucksBook needs sleep -> The default is 60 seconds (can be changed by `--sleep-before-start` option)~~
* Users of third-party programs need to write valid configuration (see the example below)
* Users can specify alternative configuration file (the default is …
> Allow to parse configuration file for third-party programs and start the programs

- truckersmp_cli/configfile.py
- truckersmp_cli/gamestarter.py
- truckersmp_cli/main.py
- truckersmp_cli/steamruntime_helper.py
Fixes #203.
Details:
* https://github.com/truckersmp-cli/truckersmp-cli/pull/204#issuecomment-873506092
* https://github.com/truckersmp-cli/truckersmp-cli/pull/204#issuecomment-893443565
Notes:
* As of the first commit, the waiting time after starting `wine-discord-ipc-bridge` is *hardcoded to 5 seconds*
* `--early-executable` and `--early-wait-before-start` options have been added to `steamruntime_helper.py`
> Allow to start wine-discord-ipc-bridge before starting third-party programs when the user wants

- truckersmp_cli/configfile.py
When the game specific section doesn't exist in the configuration file (or the file is not present), `parser[Args.game].getboolean("without-rich-presence", fallback=False)` raises `KeyError`.
This PR fixes the regression.
> configfile.py: Check whether config file has game specific section before loading

- README.md
- truckersmp_cli/args.py
- truckersmp_cli/configfile.py
- truckersmp_cli/gamestarter.py
- truckersmp_cli/utils.py
Part of #208
It seems that [SCS Software is working on supporting D3D12 or (and?) Vulkan](https://forum.scssoft.com/viewtopic.php?f=41&t=301222).
Currently we can only choose whether to use D3D11 (or OpenGL) and we should be able to specify rendering backend name.
Option: `--rendering-backend {auto,dx11,gl}` (`-r {auto,dx11,gl}`)
Game specific setting (`[ets2mp]`, `[ets2]`, `[atsmp]`, `[ats]`, or `[DEFAULT]` section): `rendering-backend = {dx11,gl}`
`--enable-d3d11` (`-d`) option
> Allow to specify rendering backend name

- truckersmp_cli/configfile.py
Part of #208
It seems that some users need to disable Steam Runtime for some reasons: See #202
Game specific setting (`[ets2mp]`, `[ets2]`, `[atsmp]`, `[ats]`, or `[DEFAULT]` section): `without-steamruntime = [boolean]`
> configfile.py: Allow to specify whether to disable Steam Runtime

- truckersmp_cli/args.py
See https://docs.python.org/3/library/argparse.html#type
> By default, the parser reads command-line arguments in as simple strings.
> args.py: Omit "type=str" for add_argument()

- truckersmp_cli/args.py
- truckersmp_cli/configfile.py
Part of #208
See also #163
Game specific setting (`[ets2mp]`, `[ets2]`, `[atsmp]`, `[ats]`, or `[DEFAULT]` section): `game-options = [options]`
> args.py, configfile.py: Allow to specify game options in configuration file

- truckersmp_cli/main.py
See https://github.com/truckersmp-cli/truckersmp-cli/pull/156#issuecomment-784418013
I'd like to apply this change before allowing users to set TruckersMP MOD directory using config file.
> main.py: Drop fallback to old local folder

- truckersmp_cli/utils.py
Fix #238
We should have replaced this `dest` with `dest["abspath"]` (for the absolute path to the destination file) in #226.
> download_files(): Fix TypeError when HTTP redirected

- truckersmp_cli/configfile.py
- truckersmp_cli/main.py
Part of #208
Game specific setting (`[ets2mp]`, `[ets2]`, `[atsmp]`, `[ats]`, or `[DEFAULT]` section): `truckersmp-directory = [path]`
> configfile.py, main.py: Allow to specify TruckersMP MOD directory

- README.md
- truckersmp_cli/args.py
- truckersmp_cli/steamcmd.py
- truckersmp_cli/utils.py
Closes #231
This PR adds `--download-throttle=SPEED` option (KiB/s).
When the option is given, it limits download speed:
* `SteamCMD.run()`: Add `set_download_throttle` command to SteamCMD (See https://github.com/truckersmp-cli/truckersmp-cli/issues/231#issuecomment-907712126)
* `write_downloaded_file()`: Wait if the speed is too fast (For TruckersMP MOD files, wine-discord-ipc-bridge, and `d3dcompiler_47.dll`)
> Allow to limit download speed

- .github/workflows/auto_release.yaml
This allows developers to release stable versions from stable branches.
> GitHub Actions: Allow to run automatic release jobs on every branch

- .github/workflows/auto_release.yaml
Without this change, GitHub Actions releases a new version even when changing `RELEASE` file for "Release [version]" PRs.
> GitHub Actions: Allow to run automatic release jobs only on main or stable branches

- truckersmp_cli/args.py
- truckersmp_cli/configfile.py
Part of #208
Game specific setting (`[ets2mp]`, `[ets2]`, `[atsmp]`, `[ats]`, or `[DEFAULT]` section):
* `game-directory = [path]`
* `prefix-directory = [path]`
> args.py, configfile.py: Allow to specify "{game,prefix}-directory" settings

- README.md
- truckersmp_cli/args.py
Since #90 was fixed (upstream), this option is not necessary for this purpose. However, some users need the option to work around resolution issue (e.g. https://github.com/truckersmp-cli/truckersmp-cli/issues/257#issuecomment-978035584).
> README.md, args.py: Update description for "--wine-desktop" option

- truckersmp_cli/steamcmd.py
This fixes `Please use force_install_dir before logon!` message when running SteamCMD.
This might be related to #189 but not sure if this fixes it.
> steamcmd.py: Execute force_install_dir before login

- truckersmp_cli/args.py
- truckersmp_cli/configfile.py
- truckersmp_cli/main.py
Part of #208
Game specific setting (`[ets2mp]`, `[ets2]`, `[atsmp]`, `[ats]`, or `[DEFAULT]` section):
* `proton-directory = [path]`
* `steamruntime-directory = [path]`
> args.py, configfile.py, main.py: Allow to specify "{proton,steamruntime}-directory" settings

- truckersmp_cli/args.py
- truckersmp_cli/configfile.py
Part of #208
Game specific setting (`[ets2mp]`, `[ets2]`, `[atsmp]`, `[ats]`, or `[DEFAULT]` section):
* `disable-proton-overlay = [boolean]`
> args.py, configfile.py: Allow to specify whether to disable Steam Overlay for Proton

- README.md
- truckersmp_cli/args.py
Already dropped in PR #237 (We should have removed in the PR).
> README.md, args.py: Remove already dropped fallback MOD directory from help

- README.md
- truckersmp_cli/args.py
- truckersmp_cli/configfile.py
- truckersmp_cli/gamestarter.py
- truckersmp_cli/main.py
- truckersmp_cli/steamcmd.py
We already have `*steamruntime*` options/settings but `--without-steam-runtime` contains `steam-runtime`, not `steamruntime`.
> Rename --without-steam-runtime/without-steamruntime to --disable-steamruntime/disable-steamruntime

- truckersmp_cli/utils.py
Proton/multiplayer verbose output example:
```
** INFO **  Running Steam Runtime helper:
SteamAppId=227300
SteamGameId=227300
PROTON_USE_WINED3D=0
STEAM_COMPAT_CLIENT_INSTALL_PATH=/home/user/.steam
STEAM_COMPAT_DATA_PATH=/home/user/.local/share/truckersmp-cli/Euro Truck Simulator 2/prefix
python3
/home/user/.local/share/truckersmp-cli/Proton/proton
run
/path/to/truckersmp-cli/truckersmp_cli/truckersmp-cli.exe
/home/user/.local/share/truckersmp-cli/Euro Truck Simulator 2/data
/home/user/.local/share/truckersmp-cli/TruckersMP
-rdevice dx11 -nointro -64bit
```
Wine/singleplayer verbose output example:
```
** INFO **  Running Wine:
WINEARCH=win64
WINEDEBUG=-all
WINEDLLOVERRIDES=
WINEPREFIX=/home/user/.wine-truckersmp
wine
/home/user/.local/share/truckersmp-cli/Euro Truck Simulator …
```
> log_info_formatted_envars_and_args(): Print all game options in one line

- truckersmp_cli/gamestarter.py
As of 0.8.1, `StarterProton` does not start game when not specifying `-v` or `-vv`.
This PR fixes the issue.
> StarterProton: Always wait for helper process to terminate

- README.md
- truckersmp_cli/args.py
- truckersmp_cli/configfile.py
- truckersmp_cli/flatpak_helper.py
- truckersmp_cli/gamestarter.py
- truckersmp_cli/steamcmd.py
- truckersmp_cli/variables.py
Closes #52
This PR allows to start games using Flatpak version of Steam.
* Steam Runtime can't be used in Flatpak container
* Steam Runtime wants `dbus-launch` but the Flatpak container doesn't provide it (as of Jan 2022)
* IMO, if ETS2 and ATS (including TruckersMP) work in the Flatpak container, Steam Runtime container is unnecessary: Currently no need to use Steam Runtime
* Even when Flatpak version of Steam is already running, `truckersmp-cli` needs to launch it via our new helper script `flatpak_helper.py` in order to be able to start games
* If Flatpak version of Steam is already running, truckersmp-cli kills it before starting Steam
`-f`/`--flatpak-steam`
`flatpak-steam = [boolean (true)]`
Example:
```ini
[DEFAULT]
flatpak-steam = yes
```
> Allow to use Flatpak version of Steam

- truckersmp_cli/steamcmd.py
`truckersmp-cli` doesn't need to show this message even when failing, because it only makes sure that Steam is not running.
We *can check* whether Flatpak version of Steam is already running by `flatpak ps`, but `truckersmp-cli` needs to execute 2 commands (`flatpak ps` and `flatpak kill`) when running.
> update_game(): Suppress error when failing to close Flatpak version of Steam

- README.md
- truckersmp_cli/args.py
- truckersmp_cli/steamcmd.py
* `-i 6.3` = `-i 1580130`
* `-i 5.13` = `-i 1420170`
* `-i 5.0` = `-i 1245040`
* `-i 4.11` = `-i 1113280`
> Allow to specify Proton version ("X.Y" format) instead of AppId

- truckersmp_cli/args.py
This fixes `AttributeError: 'int' object has no attribute 'startswith'` error when installing Proton with `X.Y` version string.
> args.py: Store Args.proton_appid as string when Proton version string is given

- README.md
The current sample configuration file doesn't work when `atsmp` or `ets2` is specified: The settings in `[DEFAULT]` section are not applied.
The fix is to add empty `[atsmp]` and `[ets2]` sections.
> README.md: Add empty game mode specific sections to sample configuration file

- setup.cfg
We changed the version requirement in PR #240 (Milestone:0.8.0).
> Setup.cfg: Set python_requires to >=3.6

- truckersmp_cli/steamcmd.py
- truckersmp_cli/utils.py
This PR supersedes #316 (security fix for CVE-2007-4559)
> steamcmd.py, utils.py: Don't unpack tar archives that can perform directory traversal attack

- truckersmp_cli/utils.py
`0` is a valid (minor) version number.
> is_d3dcompiler_setup_skippable(): Set initial version values to (-1, -1)

- README.md
- truckersmp_cli/args.py
- truckersmp_cli/gamestarter.py
- truckersmp_cli/main.py
- truckersmp_cli/utils.py
The new action (`kill`) allows users to run `wineserver -k` from our script.
* Proton: `(protondir)/{dist,files}/bin/wineserver` with/without Steam Runtime
* Wine: `$WINESERVER` or `wineserver`
This may work around for #216: I can reproduce the error if I start a process in the same prefix beforehand, and can't reproduce after running the action.
> Add an action for killing active processes

- truckersmp_cli/utils.py
This was introduced in https://github.com/truckersmp-cli/truckersmp-cli/pull/287 and seems to be a plausible cause of #345 
@Synthron Since you seem versatile in python, may I ask you to give this a try?
fix #345
> Avoid using the "**" pattern

- .github/workflows/auto_release.yaml
This should fix `ModuleNotFoundError: No module named 'setuptools'`.
> GitHub Actions: Install setuptools before uploading package to PyPI
