truckersmp-cli/truckersmp-cli

truckersmp-cli

So let's turn around that stuff…

Well, they've changed it again?

---

truckersmp-cli

This PR doesn't change any behavior, only simplifying.
It's enough to use `+=`.

start_with_{proton,wine}(): Don't use "for statement + append()"

---

README.md
truckersmp-cli

This makes some popular choices as default.
* ETS2
* Proton
* Start
* Update
----
I wasn't sure about making _update_ the default. But I think it's better to have it _just work_ on a new system. The downside is that it's closing steam by default.

Sane defaults

---

README.md

Installation guide for bash/zsh completion.

README.md: Add sections for bash/zsh completion

---

.github/workflows/check_proton_json.yaml
README.md
truckersmp_cli/__init__.py

Some reordering and taking the latest changes into account (#76 #77 #82).

Miscellaneous release preparations

---

README.md
truckersmp_cli/__init__.py

* Remove mentions of `WINEPREFIX` because we're overwriting the variable
* Adjust wording and example to #83

Minor README enhancements

---

.pylintrc
truckersmp_cli/args.py
truckersmp_cli/main.py
truckersmp_cli/steamcmd.py
truckersmp_cli/truckersmp.py
truckersmp_cli/utils.py
truckersmp_cli/variables.py

This is the preparation work for adding pylint checking.

Fix or suppress pylint errors and warnings

---

truckersmp_cli/steamcmd.py
truckersmp_cli/truckersmp.py

The new function name is `determine_game_branch()`.
See also https://github.com/lhark/truckersmp-cli/pull/98#issuecomment-672885230

truckersmp.py: Combine get_beta_branch_name() with determine_game_branch()

---

README.md

Only reordering. The contents are not changed.

README.md: Make it easy for users to find dependencies and how to install

---

README.md

README.md: Describe known issues that are related to rendering backends

---

README.md
truckersmp_cli/args.py
truckersmp_cli/main.py
truckersmp_cli/utils.py
truckersmp_cli/variables.py

Support Discord rich presence via wine-discord-ipc-bridge

---

truckersmp_cli/utils.py
truckersmp_cli/variables.py

Some fixes and refactoring related to download_files()

---

truckersmp_cli/variables.py

Update Wine Discord IPC Bridge to 0.0.1

---

truckersmp_cli/truckersmp.py
truckersmp_cli/variables.py

truckersmp.py, variables.py: Rewrite downgrade checking

---

truckersmp_cli/utils.py

* Add "/f" option
* Don't use list

Fixes in activate_native_d3dcompiler_47()

---

truckersmp_cli/main.py

When switching from newer Proton version to older, the native `d3dcompiler_47.dll` is removed by downgrading prefix automatically.
This PR only fixes the behavior when `--activate-native-d3dcompiler-47` is specified *and* Proton version is changed. We still cannot protect the native DLL.

start_with_proton(): Make sure the prefix is already upgraded/downgraded before copying native d3dcompiler_47

---

README.md
truckersmp_cli/args.py

workaround #129 
We should test if the same happens with wine steam.

Document game installation

---

README.md
truckersmp_cli/args.py
truckersmp_cli/utils.py

~~For users who don't save account credentials on their computers.~~
~~Note: We recommend that such users start Steam and login beforehand. Otherwise they would need to wait 99 seconds.~~

Add "--native-steam-dir" option

---

truckersmp_cli/main.py

main.py: Fix C0326

---

truckersmp_cli/utils.py

```
(Downloading)
[11/22] Get: filename.ext                          512.0K / 666.6K [=======>  ]
(Done)
filename.ext                                                       [    OK    ]
```
* 10 steps, 10 characters (10% = 1 char)
* Downloading: `>`
* Downloaded: `=`
```
$ python3
>>> for ten_percent_count in range(11):
...     "[{}{}{}] {}%{}".format("=" * ten_percent_count, ">" if ten_percent_count < 10 else "", " " * max(9 - ten_percent_count, 0), ten_percent_count * 10, "-{}%".format(ten_percent_count * 10 + 9) if ten_percent_count < 10 else "")
...
'[>         ] 0%-9%'
'[=>        ] 10%-19%'
'[==>       ] 20%-29%'
'[===>      ] 30%-39%'
'[====>     ] 40%-49%'
'[=====>    ] 50%-59%'
'[======>   ] 60%-69%'
'[=======>  ] 70%-79%'
'[========> ] 80%-89%'
'[=========>] 90%-99%' …
```

download_files(): Improve output (allow to print KiB/MiB size, add progress bar, change layout)

---

truckersmp_cli/main.py
truckersmp_cli/variables.py

For #88, #92, #120, and #140.
When it's missing, the script prints an error message and instructions.

main.py, variables.py: Check whether the executable of our inject program is present

---

truckersmp_cli/main.py

We use `dist/bin/wine` directly when `--activate-native-d3dcompiler-47` or `--wine-desktop` option is specified, but Proton's "dist" directory doesn't exist when SteamCMD finished installation:
```
$ ls /home/user/.local/share/truckersmp-cli/Proton
steamapps    filelock.py               proton_dist.tar          version
LICENSE      proton                    toolmanifest.vdf
LICENSE.OFL  proton_3.7_tracked_files  user_settings.sample.py
```
This PR allows to check `dist/bin/wine` and run `wineboot` for unpacking Proton's "dist" tarball when the executable is missing.
(Note: `proton` script automatically unpacks the "dist" tarball before running a program for the first time.)

start_with_proton(): Make sure Proton's "dist" directory is present

---

README.md

README.md: Add "Known issues" section and describe ProMods issue

---

README.md

With some additional description (mostly workarounds related).

README.md: Move rendering backend related known issues to "Known issues"

---

.github/workflows/build_and_upload_inject_program.yaml
truckersmp_cli/args.py

Fix bad merging

---

README.md

Add savegame info

---

truckersmp_cli/main.py

Allow to use "files/bin/wine" for proton-tkg

---

truckersmp_cli/main.py
truckersmp_cli/utils.py
truckersmp_cli/variables.py

See https://github.com/truckersmp-cli/truckersmp-cli/pull/159#issuecomment-846528645
Depends on #181

Share Steam library directories when starting singleplayer game

---

setup.cfg

setup.cfg: Add steamruntime.json to options.package_data

---

truckersmp_cli/utils.py

adding proton-tkg support mayor-minor

get_proton_version(): Add support for proton-tkg

---

truckersmp_cli/steamruntime_helper.py
truckersmp_cli/utils.py

steamruntime_helper.py, utils.py: Suppress R1732

---

truckersmp_cli/utils.py

get_steam_library_dirs(): Support the new format of libraryfolders.vdf

---

README.md

https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.getboolean

README.md: {on,off} can be used as boolean

---

truckersmp_cli/steamruntime_helper.py

steamruntime_helper.py: Fix starting game when nonverbose

---

README.md
truckersmp_cli/args.py
truckersmp_cli/configfile.py
truckersmp_cli/gamestarter.py
truckersmp_cli/main.py
truckersmp_cli/steamcmd.py
truckersmp_cli/truckersmp.py
truckersmp_cli/utils.py

To fix C0209, we need to change [Python version requirement](https://github.com/truckersmp-cli/truckersmp-cli/#required) to [version 3.6.0 (Dec 23, 2016)](https://www.python.org/downloads/release/python-360/) because [f-strings was introduced in 3.6.0](https://docs.python.org/3/whatsnew/3.6.html#pep-498-formatted-string-literals).
I'd like to change the version requirement ~~in 2022 (or Dec 2021)~~ and migrate to f-strings (= fix the errors) at the same time.

Fix R1714 and C0209

---

gen_completions

This fixes pylint error in PR 243.

gen_completions: Fix W1514 and C0209

---

.github/workflows/auto_release.yaml
.github/workflows/build_and_upload_inject_program.yaml
.github/workflows/check_gen_completions.yaml
.github/workflows/check_main_script.yaml
.github/workflows/check_proton_json.yaml

GitHub Actions: Change default branch name to "main"

---

.github/workflows/check_gen_completions.yaml
.github/workflows/check_main_script.yaml
setup.cfg

`flake8` options can be configured in `setup.cfg`: See https://flake8.pycqa.org/en/latest/user/configuration.html

setup.cfg: Set max-line-length for flake8

---

README.md

TruckersMP fixed the bug in version 0.2.3.5.0: See https://github.com/truckersmp-cli/truckersmp-cli/issues/91#issuecomment-947841618

README.md: Remove GL color picker bug description from known issues

---

README.md

README.md: Add DLC description to known issues

---

truckersmp_cli/configfile.py

configfile.py: Check whether game specific setting exists in {configure,determine}* methods

---

truckersmp_cli/args.py
truckersmp_cli/configfile.py

This allows to remove some `{configure,determine}*` methods.

args.py, configfile.py: Introduce helper methods for game specific settings

---

README.md

README.md: Describe game specific settings

---

truckersmp_cli/args.py
truckersmp_cli/configfile.py
truckersmp_cli/logger.py
truckersmp_cli/main.py

Part of #208
Game specific setting (`[ets2mp]`, `[ets2]`, `[atsmp]`, `[ats]`, or `[DEFAULT]` section): `log-file = [path]`

Allow to specify log file in configuration file

---

README.md
truckersmp_cli/args.py

* Changes based on some feedbacks from https://github.com/truckersmp-cli/truckersmp-cli/pull/271#issuecomment-1001057820
* Add Issue #248 to known issues

Misc README updates before 0.8.0

---

truckersmp_cli/steamruntime_helper.py

steamruntime_helper.py: Always wait for Proton process to terminate

---

truckersmp_cli/utils.py
truckersmp_cli/variables.py

https://github.com/0e4ef622/wine-discord-ipc-bridge/releases/tag/v0.0.2

Update ipc-bridge to 0.0.2

---

truckersmp_cli/gamestarter.py

I guess it was broken since #159 ~~211~~.

StarterProton: Set up wine-discord-ipc-bridge if using it

---

truckersmp_cli/args.py

This PR drops the following options to drop the old syntax:
* `--ets2`/`-e`
* `--ats`/`-a`
* `--singleplayer`
* `--start`/`-s`
* `--update`/`-u`
* `--downgrade`

Drop old syntax

---

README.md

Old link: https://github.com/truckersmp-cli/truckersmp-cli#default-directories
New link: https://github.com/truckersmp-cli/truckersmp-cli#game-logs

README.md: Update "Game logs" section URL

---

truckersmp_cli/utils.py

get_proton_version(): Add support for experimental{,-bleeding-edge}
